# Generated by Django 4.2.7 on 2023-11-24 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/img/events/'),
            preserve_default=False,
        ),
    ]
